services:
    metamodels.filter_select.factory:
        class: MetaModels\FilterSelectBundle\FilterSetting\SelectFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }
